version: "3.7"

services:
  shell:
    tty: true
    stdin_open: true
    build:
      context: $PWD/docker/shell
    image: josephcopenhaver/discord-bot--shell:${GIT_SHA:-latest}
    entrypoint: bash
    networks:
      - infrastructure
      - frontend
