version: "3.7"

services:
  melody-bot:
    platform: linux/amd64 # TODO: support aarch64 | arm
    build:
      context: $PWD
      dockerfile: $PWD/docker/default/Dockerfile
    env_file:
      - $PWD/secrets/$ENV.env
    volumes:
      - $PWD/.media-cache:/workspace/.media-cache
    networks:
      - infrastructure
      - frontend
