version: "3.7"

services:
  discord-bot:
    build:
      context: $PWD
      dockerfile: $PWD/docker/default/Dockerfile
    cap_add:
      - SYS_NICE
    env_file:
      - $PWD/secrets/$ENV.env
    volumes:
      - $PWD/.media-cache:/workspace/.media-cache
    networks:
      - infrastructure
      - frontend
