#!/bin/bash

set -euo pipefail

VERSION="$(head -1 version.txt)"
GIT_SHA="$(git log --pretty=format:'%H' -n 1)"

mkdir -p build/bin

go mod vendor

if [ -e vendor/github.com/josephcopenhaver/gopus/.git ]; then
    # the above vendor command removes the gopus C'linked dependency
    #
    # lets make sure that's a consistent goal
    echo "vendor/github.com/josephcopenhaver/gopus/.git should not exist!"
    exit 1
fi

# TODO: wow, does not appear to be a better way atm
# just conna hack it
# ref: https://github.com/golang/go/issues/26366
#
# install specific verion of josephcopenhaver/gopus with cgo files
JOSEPHCOPENHAVER_GOPUS_GIT_SHA=17c317f9c9e9545df42c4ffc0bb9252ee6261868
(
    set -eo pipefail

    if [ ! -d vendor/github.com/josephcopenhaver/gopus ] || [ ! -d vendor/github.com/josephcopenhaver/gopus/.git ] || [[ "$(cd gopus && git log -1 --format=%H)" != "$JOSEPHCOPENHAVER_GOPUS_GIT_SHA" ]]; then
        mkdir -p vendor-ext/github.com/josephcopenhaver
        cd vendor-ext/github.com/josephcopenhaver
        if [ ! -d gopus ] || [ ! -d gopus/.git ] || [[ "$(cd gopus && git log -1 --format=%H)" != "$JOSEPHCOPENHAVER_GOPUS_GIT_SHA" ]]; then
            rm -rf gopus
            git clone https://github.com/josephcopenhaver/gopus.git
            cd gopus
            git reset --hard "$JOSEPHCOPENHAVER_GOPUS_GIT_SHA"
            cd ..
        fi

        echo ""
        echo "rsync'ing vendor-ext/github.com/josephcopenhaver/gopus"
        echo ""

        rsync -an --delete gopus ../vendor/github.com/josephcopenhaver/gopus
    fi
)

# TODO: statically compile or have release image use the shell as a base image

set -x

# export FFMPEG_ROOT=$HOME/ffmpeg
# export CGO_LDFLAGS="-L$FFMPEG_ROOT/lib/ -lavcodec -lavformat -lavutil -lswscale -lswresample -lavdevice -lavfilter"
# export CGO_CFLAGS="-I$FFMPEG_ROOT/include -O3"
# export LD_LIBRARY_PATH=$HOME/ffmpeg/lib

export CGO_CFLAGS="-O3"

CGO_ENABLED=1 go build \
    -o build/bin/ \
    -tags netgo \
    -ldflags "-extldflags=-static -X main.GitSHA=${GIT_SHA} -X main.Version=${VERSION}" \
    ./cmd/...
